spring.application.name=studious

# Google OAuth Configuration
# TEAM: PLEASE LOOK AT TEAMS FOR THE CID AND CSECRET. PLACE IT IN THE TWO CLIENT.ID'S BELOW AFTER THE COLON
google.client.id=${GOOGLE_CLIENT_ID:850109297022-j7nkq31qo6f3tv8snim2cqf24sedqjet.apps.googleusercontent.com}
google.client.secret=${GOOGLE_CLIENT_SECRET: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}
google.redirect.uri=http://localhost:8080/auth/google/callback
google.scopes=openid,email,https://www.googleapis.com/auth/calendar.readonly,https://www.googleapis.com/auth/calendar.events

# Canvas LMS Configuration
canvas.url=${CANVAS_URL:https://canvas.instructure.com}
canvas.token=${CANVAS_TOKEN:7~9eGVKPMGPCYeCnFZFFBxV74RnTXXXuxUywEE97FLPmH9hvQyaRPAmcZzWmAfmvJ7}
