spring.application.name=studious

# Google OAuth Configuration
# TEAM: PLEASE LOOK AT TEAMS FOR THE CID AND CSECRET. PLACE IT IN THE TWO CLIENT.ID'S BELOW AFTER THE COLON
google.client.id= #REPLACE ME CID
google.client.secret= #REPLACE ME CSECRET
google.redirect.uri=http://localhost:8080/auth/google/callback
google.scopes=https://www.googleapis.com/auth/calendar.readonly,https://www.googleapis.com/auth/calendar.events
