spring.application.name=studious

# Google OAuth Configuration
google.client.id=850109297022-j7nkq31qo6f3tv8snim2cqf24sedqjet.apps.googleusercontent.com
google.client.secret=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
google.redirect.uri=http://localhost:8080/auth/google/callback
google.scopes=https://www.googleapis.com/auth/calendar.readonly,https://www.googleapis.com/auth/calendar.events
